ignore:
  - .git
  - .venv
  - venv
  - __pycache__
  - sample_outputs
  - test_assets

rule_settings:
  enable:
    - default
  disable: []
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: "3.10"

metrics:
  quality_threshold: 25.0

github:
  labels: []
  ignore_labels:
    - sourcery-ignore
  request_review: author
  sourcery_branch: sourcery/{base_branch}
